### ISSUE TITLE
Why ~2 is -3 and not 1?

### ISSUE THREAD

**Issue by peeush-the-developer** [PAVANINADELLA/DATA-SCIENCE-NOTES#5]
Hello @PAVANINADELLA,
I didn't understand the result of this `~2`.

```
2 => 1 0
~ => 0 1 => 1 # Why it is -3 in Python?
```

![image](https://user-images.githubusercontent.com/77566602/116522016-4cdc7380-a8f2-11eb-8a4e-a571fb162797.png)

Could you please explain this result?

**Comment by PAVANINADELLA** [comment]
Hello.
Good Morning.

Here is the answer for your question: 
Python's Tilde ~n operator is the bitwise negation operator i.e., it takes the number n as binary number and “flips” all bits 0 to 1 and 1 to 0 to obtain the complement binary number.
 For example, the tilde operation ~1 becomes 0, ~0 becomes 1 and ~101 becomes 010.

Thank you & Regards,
PAVANI NADELLA.

**Comment by PAVANINADELLA** [comment]
Hello.

In this example, after toggling all bits of 14 (00001110), you get 11110001 in binary. 
Since the leftmost bit is 1, it is a negative number. 
So, after ignoring the leftmost 1, you should toggle all bits (000 1110) and add 1 (000 1110 + 1 = 0001111) to the result to get the number in decimal notation. 
Therefore, Prefix a minus (-) symbol before the result and It becomes -15.

In other words, to convert a negative binary number to decimal, you should do One's complement and add 1 to the result. This is also called 2's complement.

Here is the Code:
x = 14; #00001110
print(x, '=', bin(x))
print(~x) #1111 0001
print(bin(~x))

Output of the Code:
14 = 0b1110
-15
-0b1111

Kindly go through it and check.

Thank you & Regards.,
PAVANI NADELLA.

**Comment by peeush-the-developer** [comment]
Thanks, @PAVANINADELLA, for the explanation. I got it now.
